[tool.black]
line-length = 88
skip-string-normalization = false

[tool.isort]
profile = "black"
line_length = 88

[tool.pyright]
typeCheckingMode = "basic"

[tool.flake8]
max-line-length = 88
exclude = [
    "backend/venv",
    "backend/__pycache__",
    "backend/**/__pycache__",
    "backend/logs",
    "backend/htmlcov",
    "backend/.pytest_cache",
    "temp_downloads",
    "temp_job_cache",
    "karaoke_library"
]
ignore = ["E203", "W503"]