"""Make duration_ms nullable in songs table

Revision ID: d048757b81a8
Revises: 20250622_duration_ms_migration
Create Date: 2025-07-06 19:35:29.658971

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d048757b81a8"
down_revision: Union[str, None] = "20250622_duration_ms_migration"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema for SQLite: make duration_ms nullable."""
    # 1. Create new table with duration_ms nullable
    op.create_table(
        "songs_new",
        sa.Column("id", sa.String, primary_key=True),
        sa.Column("title", sa.String, nullable=False),
        sa.Column("artist", sa.String, nullable=False),
        sa.Column("duration_ms", sa.Integer, nullable=True),
        sa.Column("favorite", sa.Boolean, default=False),
        sa.Column("date_added", sa.DateTime, nullable=True),
        sa.Column("vocals_path", sa.String, nullable=True),
        sa.Column("instrumental_path", sa.String, nullable=True),
        sa.Column("original_path", sa.String, nullable=True),
        sa.Column("thumbnail_path", sa.String, nullable=True),
        sa.Column("cover_art_path", sa.String, nullable=True),
        sa.Column("source", sa.String, nullable=True),
        sa.Column("source_url", sa.String, nullable=True),
        sa.Column("video_id", sa.String, nullable=True),
        sa.Column("uploader", sa.String, nullable=True),
        sa.Column("uploader_id", sa.String, nullable=True),
        sa.Column("channel", sa.String, nullable=True),
        sa.Column("channel_id", sa.String, nullable=True),
        sa.Column("description", sa.Text, nullable=True),
        sa.Column("upload_date", sa.DateTime, nullable=True),
        sa.Column("mbid", sa.String, nullable=True),
        sa.Column("album", sa.String, nullable=True),
        sa.Column("release_id", sa.String, nullable=True),
        sa.Column("release_date", sa.String, nullable=True),
        sa.Column("year", sa.Integer, nullable=True),
        sa.Column("genre", sa.String, nullable=True),
        sa.Column("language", sa.String, nullable=True),
        sa.Column("lyrics", sa.Text, nullable=True),
        sa.Column("synced_lyrics", sa.Text, nullable=True),
        sa.Column("channel_name", sa.String, nullable=True),
        sa.Column("itunes_artist_id", sa.Integer, nullable=True),
        sa.Column("itunes_collection_id", sa.Integer, nullable=True),
        sa.Column("track_time_millis", sa.Integer, nullable=True),
        sa.Column("itunes_explicit", sa.Boolean, nullable=True),
        sa.Column("itunes_preview_url", sa.String, nullable=True),
        sa.Column("itunes_artwork_urls", sa.Text, nullable=True),
        sa.Column("youtube_thumbnail_urls", sa.Text, nullable=True),
        sa.Column("youtube_tags", sa.Text, nullable=True),
        sa.Column("youtube_categories", sa.Text, nullable=True),
        sa.Column("youtube_channel_id", sa.String, nullable=True),
        sa.Column("youtube_channel_name", sa.String, nullable=True),
        sa.Column("youtube_raw_metadata", sa.Text, nullable=True),
    )
    # 2. Copy data from old table to new table
    op.execute(
        """
        INSERT INTO songs_new (
            id, title, artist, duration_ms, favorite, date_added, vocals_path, instrumental_path, original_path, thumbnail_path, cover_art_path, source, source_url, video_id, uploader, uploader_id, channel, channel_id, description, upload_date, mbid, album, release_id, release_date, year, genre, language, lyrics, synced_lyrics, channel_name, itunes_artist_id, itunes_collection_id, track_time_millis, itunes_explicit, itunes_preview_url, itunes_artwork_urls, youtube_thumbnail_urls, youtube_tags, youtube_categories, youtube_channel_id, youtube_channel_name, youtube_raw_metadata
        )
        SELECT
            id, title, artist, duration_ms, favorite, date_added, vocals_path, instrumental_path, original_path, thumbnail_path, cover_art_path, source, source_url, video_id, uploader, uploader_id, channel, channel_id, description, upload_date, mbid, album, release_id, release_date, year, genre, language, lyrics, synced_lyrics, channel_name, itunes_artist_id, itunes_collection_id, track_time_millis, itunes_explicit, itunes_preview_url, itunes_artwork_urls, youtube_thumbnail_urls, youtube_tags, youtube_categories, youtube_channel_id, youtube_channel_name, youtube_raw_metadata
        FROM songs;
        """
    )
    # 3. Drop old table
    op.drop_table("songs")
    # 4. Rename new table to songs
    op.rename_table("songs_new", "songs")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("songs", "duration_ms", existing_type=sa.INTEGER(), nullable=False)
    op.create_table(
        "songs_new",
        sa.Column("id", sa.VARCHAR(), nullable=False),
        sa.Column("title", sa.VARCHAR(), nullable=False),
        sa.Column("artist", sa.VARCHAR(), nullable=False),
        sa.Column("album", sa.VARCHAR(), nullable=True),
        sa.Column("duration_ms", sa.INTEGER(), nullable=False),
        sa.Column("favorite", sa.BOOLEAN(), nullable=True),
        sa.Column("date_added", sa.DATETIME(), nullable=True),
        sa.Column("vocals_path", sa.VARCHAR(), nullable=True),
        sa.Column("instrumental_path", sa.VARCHAR(), nullable=True),
        sa.Column("original_path", sa.VARCHAR(), nullable=True),
        sa.Column("thumbnail_path", sa.VARCHAR(), nullable=True),
        sa.Column("cover_art_path", sa.VARCHAR(), nullable=True),
        sa.Column("source", sa.VARCHAR(), nullable=True),
        sa.Column("source_url", sa.VARCHAR(), nullable=True),
        sa.Column("video_id", sa.VARCHAR(), nullable=True),
        sa.Column("uploader", sa.VARCHAR(), nullable=True),
        sa.Column("uploader_id", sa.VARCHAR(), nullable=True),
        sa.Column("channel", sa.VARCHAR(), nullable=True),
        sa.Column("channel_id", sa.VARCHAR(), nullable=True),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("upload_date", sa.DATETIME(), nullable=True),
        sa.Column("mbid", sa.VARCHAR(), nullable=True),
        sa.Column("release_id", sa.VARCHAR(), nullable=True),
        sa.Column("release_date", sa.VARCHAR(), nullable=True),
        sa.Column("year", sa.INTEGER(), nullable=True),
        sa.Column("genre", sa.VARCHAR(), nullable=True),
        sa.Column("language", sa.VARCHAR(), nullable=True),
        sa.Column("lyrics", sa.TEXT(), nullable=True),
        sa.Column("synced_lyrics", sa.TEXT(), nullable=True),
        sa.Column("channel_name", sa.VARCHAR(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
