"""Remove deprecated release_title column

Revision ID: addbfd875d80
Revises: 05b03e51ddf0
Create Date: 2025-06-20 23:47:16.513943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'addbfd875d80'
down_revision: Union[str, None] = '05b03e51ddf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'release_title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('release_title', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
