"""Initial Postgres schema

Revision ID: 601713691424
Revises: 
Create Date: 2025-08-09 17:38:42.221575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '601713691424'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('status_message', sa.Text(), nullable=True),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('song_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('artist', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('dismissed', sa.Boolean(), nullable=True),
    sa.Column('phase_message', sa.Text(), nullable=True),
    sa.Column('phase', sa.String(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('songs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('artist', sa.String(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('vocals_path', sa.String(), nullable=True),
    sa.Column('instrumental_path', sa.String(), nullable=True),
    sa.Column('original_path', sa.String(), nullable=True),
    sa.Column('thumbnail_path', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('video_id', sa.String(), nullable=True),
    sa.Column('uploader', sa.String(), nullable=True),
    sa.Column('uploader_id', sa.String(), nullable=True),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('channel_id', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.Column('mbid', sa.String(), nullable=True),
    sa.Column('album', sa.String(), nullable=True),
    sa.Column('release_id', sa.String(), nullable=True),
    sa.Column('release_date', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('genre', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('plain_lyrics', sa.Text(), nullable=True),
    sa.Column('synced_lyrics', sa.Text(), nullable=True),
    sa.Column('channel_name', sa.String(), nullable=True),
    sa.Column('itunes_artist_id', sa.Integer(), nullable=True),
    sa.Column('itunes_collection_id', sa.Integer(), nullable=True),
    sa.Column('track_time_millis', sa.Integer(), nullable=True),
    sa.Column('itunes_explicit', sa.Boolean(), nullable=True),
    sa.Column('itunes_preview_url', sa.String(), nullable=True),
    sa.Column('youtube_thumbnail_urls', sa.Text(), nullable=True),
    sa.Column('youtube_tags', sa.Text(), nullable=True),
    sa.Column('youtube_categories', sa.Text(), nullable=True),
    sa.Column('youtube_channel_id', sa.String(), nullable=True),
    sa.Column('youtube_channel_name', sa.String(), nullable=True),
    sa.Column('youtube_raw_metadata', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('theme', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('karaoke_queue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('singer_name', sa.String(), nullable=False),
    sa.Column('song_id', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('karaoke_queue')
    op.drop_table('users')
    op.drop_table('songs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
