"""Add Phase 1B metadata fields

Revision ID: 6e002eaf6490
Revises: 64525c88b0de
Create Date: 2025-06-07 18:26:50.168870

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6e002eaf6490"
down_revision: Union[str, None] = "64525c88b0de"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema - Add Phase 1B metadata fields."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("songs", schema=None) as batch_op:
        # iTunes integration fields
        batch_op.add_column(sa.Column("itunes_track_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("itunes_artist_id", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column("itunes_collection_id", sa.Integer(), nullable=True)
        )
        batch_op.add_column(sa.Column("track_time_millis", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("itunes_explicit", sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column("itunes_preview_url", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("itunes_artwork_urls", sa.Text(), nullable=True))

        # Enhanced YouTube fields
        batch_op.add_column(sa.Column("youtube_duration", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column("youtube_thumbnail_urls", sa.Text(), nullable=True)
        )
        batch_op.add_column(sa.Column("youtube_tags", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("youtube_categories", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("youtube_channel_id", sa.String(), nullable=True))
        batch_op.add_column(
            sa.Column("youtube_channel_name", sa.String(), nullable=True)
        )

        # Raw metadata storage
        batch_op.add_column(sa.Column("itunes_raw_metadata", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("youtube_raw_metadata", sa.Text(), nullable=True))

        # Year field (missing from Phase 1A)
        batch_op.add_column(sa.Column("year", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema - Remove Phase 1B metadata fields."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("songs", schema=None) as batch_op:
        batch_op.drop_column("year")
        batch_op.drop_column("youtube_raw_metadata")
        batch_op.drop_column("itunes_raw_metadata")
        batch_op.drop_column("youtube_channel_name")
        batch_op.drop_column("youtube_channel_id")
        batch_op.drop_column("youtube_categories")
        batch_op.drop_column("youtube_tags")
        batch_op.drop_column("youtube_thumbnail_urls")
        batch_op.drop_column("youtube_duration")
        batch_op.drop_column("itunes_artwork_urls")
        batch_op.drop_column("itunes_preview_url")
        batch_op.drop_column("itunes_explicit")
        batch_op.drop_column("track_time_millis")
        batch_op.drop_column("itunes_collection_id")
        batch_op.drop_column("itunes_artist_id")
        batch_op.drop_column("itunes_track_id")
    # ### end Alembic commands ###
